version: "3"
services:
    framework:
        build: .
        container_name: framework
        ports:
            - "5556:5555"
        
    flower:
        build: .
        command: flower -A src --port=5555
        ports:
            - "5555:5555"
        depends_on:
            - framework
